// React/chap02/src/components/TodoList.js

import React from 'react'
import './css/todos.css';

import TodoListItem from './TodoListItem'

function Todolist(props){
    
    const { todoList } = props;

    return (
        <div>
            <table className="table">
                <thead>
                    <tr>
                        <th style={{width:'10%'}}>ID</th>
                        <th>Todo</th>
                        <th style={{width:'10%'}}>Complete</th>
                        <th style={{width:'10%'}}>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    { todoList.map( item => <TodoListItem todo={item} key={item.id} /> )}
                </tbody>
            </table>
        </div>
    )
}
export default Todolist;

// Vue/chap04_todolist/src/components/TodoList.vue

<template>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th style="{width:'10%'}">ID</th>
                    <th>Todo</th>
                    <th style="{width:'10%'}">Complete</th>
                    <th style="{width:'10%'}">Delete</th>
                </tr>
            </thead>
            <tbody>
                <TodoListItem v-for="(todo, index) in todoList" :key="todo.id" :todo="todo" :index="index"></TodoListItem>
            </tbody>
        </table>
    </div>
</template>

<script>
    import TodoListItem from './TodoListItem.vue'
    export default {
        props: ['todoList'],
        components: { TodoListItem }
    }
</script>

<style scoped>

</style>
