// Vue/chap04_todolist/src/components/TodoTemplate.vue
<template>
    <div>
        <h3>TodoList</h3>
        <TodoForm></TodoForm>
        <hr>
        <TodoList :todoList="todoList"></TodoList>
    </div>    
</template>

<script>
import TodoForm from './TodoForm.vue'
import TodoList from './TodoList.vue'

const todos = [];
for(let i = 0; i < 5; i++) {
    const todo = {id: i, text: `${i}번째 할 일`, done: false};
    todos.push(todo);
}

export default {
    components: { TodoForm, TodoList },
    data: function() {
        return {
            todoList: todos
        }
    }
}
</script>

// React/chap02/src/components/TodoTemplate.js

import React, { useState } from 'react'

import TodoForm from './TodoForm'
import TodoList from './TodoList'

const makeTodo = () => {
    const todos = [];
    for(let i = 1; i <= 5; i++) {
        todos.push( {id: i, text: `${i}번째 할 일`, done: false} );
    }
    return todos;
}

const TodoTemplate = () => {

    const [todoList, setTodoList] = useState(makeTodo())

    return (
        <div>
            <h3>Todo List</h3>

            <TodoForm />
            <hr />
            <TodoList todoList={todoList} />
        </div>
    )
}
export default TodoTemplate;
